/**
 * Service worker: owns the API token, talks to the Wishing Well API, and
 * adds the "Add to wishlist" right-click entry.
 *
 * The token never lives in the page, only in chrome.storage (extension-local).
 */

/**
 * Where this build of the extension expects Wishing Well to live.
 *
 * `manifest.json` is generated by scripts/build-extension.mjs, which reads
 * WISHING_WELL_ORIGIN. That means a deployed extension is already pointed at
 * the right host, and nobody has to hand-type an address into settings after
 * installing it. The localhost value is only the zero-config default for
 * running against a local dev server.
 */
const BUILD_ORIGIN = "https://wishing-well-seven.vercel.app";
const LOCAL_DEV = "http://localhost:3000";

// A checkout that was never run through scripts/build-extension.mjs still
// carries the raw placeholder. It is a non-empty string, so a plain
// `BUILD_ORIGIN || fallback` would happily ship requests to
// "__WISHING_WELL_ORIGIN__/api/...". Only trust something that parses as a
// real http(s) origin, and fall back to the local dev server otherwise.
function resolveBuildOrigin(value) {
  if (typeof value !== "string" || value.startsWith("__")) return LOCAL_DEV;
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") return LOCAL_DEV;
    return url.origin;
  } catch {
    return LOCAL_DEV;
  }
}

const DEFAULTS = {
  server: resolveBuildOrigin(BUILD_ORIGIN),
  token: null,
  user: null,
  lastListId: null,
};

async function config() {
  const stored = await chrome.storage.local.get(DEFAULTS);
  // A stored server always wins, so someone who points the extension at a
  // self-hosted copy isn't silently moved to the build default.
  return { ...DEFAULTS, ...stored };
}

async function api(path, { method = "GET", body } = {}) {
  const { server, token } = await config();
  if (!token) throw new Error("Not signed in yet.");

  const res = await fetch(`${server}${path}`, {
    method,
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${token}`,
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || `Request failed (${res.status}).`);
  return data;
}

async function scrapeTab(tabId) {
  try {
    const res = await chrome.tabs.sendMessage(tabId, { type: "collect" });
    if (res?.ok) return res.data;
  } catch {
    /* restricted page (chrome://, the web store, a PDF) — fall through */
  }

  let tab;
  try {
    [tab] = await chrome.tabs.get(tabId);
  } catch {
    return null;
  }
  if (!tab?.url || !/^https?:/.test(tab.url)) return null;

  return {
    title: tab.title || new URL(tab.url).hostname,
    url: tab.url.split("#")[0],
    imageUrl: null,
    price: null,
    currency: "USD",
    site: new URL(tab.url).hostname.replace(/^www\./, ""),
  };
}

chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.removeAll(() => {
    chrome.contextMenus.create({
      id: "add-to-wishlist",
      title: "Add to wishlist…",
      contexts: ["page", "link", "image", "selection"],
    });
  });
});

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  await chrome.storage.local.set({
    pendingFromMenu: { tabId: tab?.id, url: info.linkUrl || info.srcUrl || null },
  });
  // Chrome 127+ can open the popup for us; older builds can't, so the user
  // clicks the toolbar icon instead. Either way the data is stored.
  try {
    if (chrome.action?.openPopup) await chrome.action.openPopup();
  } catch {
    /* not available on this browser version */
  }
});

chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  (async () => {
    try {
      switch (msg?.type) {
        case "config":
          sendResponse({ ok: true, config: await config() });
          break;

        case "save": {
          const current = await config();
          await chrome.storage.local.set({ ...msg.config, server: current.server });
          sendResponse({ ok: true });
          break;
        }

        case "login": {
          const current = await config();
          const res = await fetch(`${current.server}/api/extension/login`, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ email: msg.email, password: msg.password }),
          });
          const data = await res.json().catch(() => ({}));
          if (!res.ok) throw new Error(data.error || "Sign-in failed.");
          await chrome.storage.local.set({ token: data.token, user: data.user });
          sendResponse({ ok: true, user: data.user });
          break;
        }

        case "logout":
          await chrome.storage.local.set({ token: null, user: null, lastListId: null });
          sendResponse({ ok: true });
          break;

        case "lists": {
          const data = await api("/api/extension/lists");
          if (data.lists?.length) {
            const current = await config();
            const stillValid = data.lists.some((l) => l.id === current.lastListId);
            if (!stillValid) await chrome.storage.local.set({ lastListId: data.lists[0].id });
          }
          sendResponse({ ok: true, ...data });
          break;
        }

        case "scrape": {
          const data = await scrapeTab(msg.tabId);
          sendResponse({ ok: true, data });
          break;
        }

        case "scan": {
          let products = [];
          try {
            const res = await chrome.tabs.sendMessage(msg.tabId, { type: "scan", limit: msg.limit });
            if (res?.ok) products = res.products;
          } catch {
            /* restricted page — an empty result is the honest answer */
          }
          sendResponse({ ok: true, products });
          break;
        }

        case "add": {
          const current = await config();
          const result = await api("/api/extension/items", { method: "POST", body: msg.item });
          await chrome.storage.local.set({ lastListId: msg.item.listId });
          sendResponse({ ok: true, ...result, server: current.server });
          break;
        }

        case "addBulk": {
          const current = await config();
          const result = await api("/api/extension/items/bulk", {
            method: "POST",
            body: { listId: msg.listId, items: msg.items },
          });
          await chrome.storage.local.set({ lastListId: msg.listId });
          sendResponse({ ok: true, ...result, server: current.server });
          break;
        }

        default:
          sendResponse({ ok: false, error: "Unknown message." });
      }
    } catch (err) {
      sendResponse({ ok: false, error: err.message || String(err) });
    }
  })();
  return true;
});
